import { Roboto } from "next/font/google";
import "./globals.css";
import "@/components/scss/styles.scss";
import { AuthContextProvider } from "@/context/AuthContext";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });
import Header from "@/components/cv-create/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div>
          <AuthContextProvider>{children}</AuthContextProvider>
        </div>
      </body>
    </html>
  );
}
