import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/actions/AuthContext";

const inter = Inter({ subsets: ["latin"] });
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-4 max-w-6xl">
          <AuthContextProvider>
            {<Header />}
            {children}
          </AuthContextProvider>
        </div>
      </body>
    </html>
  );
}
